USE MASTER
CREATE DATABASE LABA1

USE LABA1
CREATE TABLE STUDENTS(
    STUDENT_ID INT PRIMARY KEY IDENTITY(1, 1),
    NAMES NVARCHAR(50),
    SURNAMES NVARCHAR(50),
    PATRONYMICS NVARCHAR(50),
    BIRTHDAYS DATE,
    GROUP_ID INT
)

USE LABA1
CREATE TABLE GROUPS(
    GROUP_ID INT PRIMARY KEY,
    NAMES NVARCHAR(10),
    COURSES INT
)

USE LABA1
CREATE TABLE PLANS(
    GROUP_ID INT,
    SUBJECT_ID INT,

    PRIMARY KEY (GROUP_ID, SUBJECT_ID)
)

USE LABA1
CREATE TABLE SUBJECTS(
    SUBJECT_ID INT PRIMARY KEY,
    SUBJECTS NVARCHAR(50),
    NUMBER_OF_HOURS_PER_SUBJECT INT
)

USE LABA1
ALTER TABLE STUDENTS
ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID)

USE LABA1
ALTER TABLE PLANS
ADD FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS(SUBJECT_ID)

USE LABA1
ALTER TABLE PLANS
ADD FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(GROUP_ID)

USE LABA1
INSERT INTO GROUPS(GROUP_ID, NAMES, COURSES)
VALUES 
    (135, 'ПО135', 1),
    (235, 'ПО235', 2),
    (335, 'ПО135', 3)

USE LABA1
INSERT INTO STUDENTS(NAMES, SURNAMES, PATRONYMICS, BIRTHDAYS, GROUP_ID)
VALUES 
    ('Федоренко', 'П', 'Р', '1997-12-25', 135),
    ('Зингел', 'О', NULL, '1985-12-25', 135),
    ('Савицкая', 'Н', NULL, '1987-09-22', 235),
    ('Ковальчук', 'М', 'Е', '1992-06-17', 235),
    ('Ковриго', 'Т', 'Р', '1992-05-13', 335),
    ('Шарапо', 'Н', NULL, '1992-08-14', 335)

USE LABA1
ALTER TABLE SUBJECTS
ALTER COLUMN SUBJECTS NVARCHAR(100)

USE LABA1
INSERT INTO SUBJECTS(SUBJECT_ID, SUBJECTS, NUMBER_OF_HOURS_PER_SUBJECT)
VALUES 
    (1, 'Физика', 200),
    (2, 'Математика', 120),
    (3, 'Основы алгоритмизации', 70),
    (4, 'Проектирование БД', 130),
    (5, 'Средства визуального программирования', 90),
    (6, 'Объектно-ориентированное программирование', 70)

USE LABA1
UPDATE GROUPS
SET NAMES = 'ПО134' WHERE NAMES = 'ПО135'

USE LABA1
UPDATE SUBJECTS
SET NUMBER_OF_HOURS_PER_SUBJECT = 120 WHERE SUBJECTS = 'Средства визуального программирования'

USE LABA1
UPDATE SUBJECTS
SET NUMBER_OF_HOURS_PER_SUBJECT = 100 WHERE SUBJECTS = 'Объектно-ориентированное программирование'

USE LABA1
ALTER TABLE SUBJECTS
ADD CERTIFICATION NVARCHAR(10)

USE LABA1
UPDATE SUBJECTS
SET CERTIFICATION = 'экзамен'

USE LABA1
UPDATE SUBJECTS
SET CERTIFICATION = 'зачет' WHERE SUBJECTS = 'Основы алгоритмизации'

USE LABA1
DELETE FROM STUDENTS
WHERE PATRONYMICS IS NULL
